### ISSUE TITLE
Incorrect distance calculation for sites (areals) when relations are used for pistes?

### ISSUE THREAD

**Issue by pm-cz** [yvecai/opensnowmap.org#11]
Hello,
it seems that if a piste (type nordic) is defined as a relation and included in the site relation, the lengths of its members are not included in the total length of the (nordic) pistes. Is this a bug, a feature or is it forbidden to use the relations this way?

Would including the "distance" value in the relation help?

Example: http://www.opensnowmap.org/?zoom=14&lat=49.57&lon=18.31712&
The Blue nordic piste (relation 4054574) has over 9km, but the total for the site is 8.8 km

**Comment by yvecai** [comment]
The site relation lengthes is computed on the server, directly from OSM data in the server's database (Postgis function St_Length_Spheroid()). The server takes into account the site relation members ways, and the route relations members (2 levels).
On the other side, the blue piste relation length is computed in the browser from the geometry returned by the server (OpenLayers function feature.geometry.getGeodesicLength()). Furthermore, the server returns the geometry to your browser in the not so exact "encoded polyline" format .
This leads to small errors, here 0.2km is ~2%. I think this is tolerable, let's say these 200m are in the descent :).

The 'distance' or 'length' tags are not used at all in these computation.

**Comment by pm-cz** [comment]
The blue one was just an example that a component is longer than the composite. The total length is 8.8 km (from PostGis), but it should be over 23 km, Blue+red+green ones on individual ways (8.8+9.1+5.1)

**Comment by yvecai** [comment]
Ah, ok. In fact I count the length of the *ways* that:
1) belong to the site
or
1) belong to a relation that belong to the site and 2) have a tag piste:type=*

So, in the site relation, there is 8.8km of *ways* that has piste:type=nordic. Members of the blue and red pistes does not have piste:type=nordic tags.
I don't know if they should, but I'm pretty convinced that piste:grooming=* and piste:difficulty=* belongs to the ways instead of the relation, IMO.
Amazing how the tagging habits leads to more than 1000 character sql queries for such a simple request :)
I try to fix, but not right now.

**Comment by pm-cz** [comment]
If this is a problem with the relation, it would be better to fix the relation instead of complicating your code. The localized page for marked pistes in Czech Republic was unclear about this, but the PisteMaps  page defines it the way you are describing it. Since it was rendered the problem was not visible.
