### ISSUE TITLE
Pistes mapped as areas and downhill direction

### ISSUE THREAD

**Issue by solitone** [yvecai/opensnowmap.org#18]
A route relation with the subtype route=piste may contain points, ways, and areas [1]. When piste:type=downhill (i.e. alpine skiing), dowhill direction is important. For ways, downhill direction is simply the way direction. For areas, though, this is not clear. I did read everything on [2] and other places, but didn't find a clear indication on how dowhill direction should be implied when considering areas.

Some people use both an area and a way, similar to what is done with rivers [3]. However, I'd rather not do this, since I feel it would clutter up piste relations. But how the incline information may be deduced then? What is your take on this? Use both a way and an area for a large section of the piste, and add both objects in the piste relation?

[1] https://wiki.openstreetmap.org/wiki/Tag:route%3Dpiste
[2] https://wiki.openstreetmap.org/wiki/Piste_Maps
[3] https://wiki.openstreetmap.org/wiki/Tag:waterway%3Driverbank

**Comment by yvecai** [comment]
Let's say that Opensnowmap does not care about directions.
However, it likes the pistes tagged as ways for the centerline for routing and ways +area=yes to be able to render the area. 

Also, having an area in a route relation is probably an heresy given the definition of said relations. Naturally, Opensnowmap will certainly make something rather ugly with such a beast :-)

Seriously, the only case where I saw the need to use relations for piste:type=downhill this were relations of type multipolygon to make complex areas (with holes). Otherwise, avoid unnecessary complexity and avoid relations.

Closing because it's not really an Opensnowmap issue, let's discuss on help.openstreetmap.org or elsewhere.
